'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace HorasMedias
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="HorasMedias.IHorasMedias")>  _
    Public Interface IHorasMedias
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorasMedias/HorasMedias", ReplyAction:="http://tempuri.org/IHorasMedias/HorasMediasResponse")>  _
        Function HorasMedias(ByVal asignatura As String) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IHorasMedias/HorasMedias", ReplyAction:="http://tempuri.org/IHorasMedias/HorasMediasResponse")>  _
        Function HorasMediasAsync(ByVal asignatura As String) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IHorasMediasChannel
        Inherits HorasMedias.IHorasMedias, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HorasMediasClient
        Inherits System.ServiceModel.ClientBase(Of HorasMedias.IHorasMedias)
        Implements HorasMedias.IHorasMedias
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HorasMedias(ByVal asignatura As String) As Double Implements HorasMedias.IHorasMedias.HorasMedias
            Return MyBase.Channel.HorasMedias(asignatura)
        End Function
        
        Public Function HorasMediasAsync(ByVal asignatura As String) As System.Threading.Tasks.Task(Of Double) Implements HorasMedias.IHorasMedias.HorasMediasAsync
            Return MyBase.Channel.HorasMediasAsync(asignatura)
        End Function
    End Class
End Namespace
