'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Pass
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Pass.ISafePass")>  _
    Public Interface ISafePass
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISafePass/esSegura", ReplyAction:="http://tempuri.org/ISafePass/esSeguraResponse")>  _
        Function esSegura(ByVal pass As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISafePass/esSegura", ReplyAction:="http://tempuri.org/ISafePass/esSeguraResponse")>  _
        Function esSeguraAsync(ByVal pass As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISafePassChannel
        Inherits Pass.ISafePass, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SafePassClient
        Inherits System.ServiceModel.ClientBase(Of Pass.ISafePass)
        Implements Pass.ISafePass
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function esSegura(ByVal pass As String) As String Implements Pass.ISafePass.esSegura
            Return MyBase.Channel.esSegura(pass)
        End Function
        
        Public Function esSeguraAsync(ByVal pass As String) As System.Threading.Tasks.Task(Of String) Implements Pass.ISafePass.esSeguraAsync
            Return MyBase.Channel.esSeguraAsync(pass)
        End Function
    End Class
End Namespace
